// Copyright 2012 Google, Inc. All rights reserved.

package layers

import (
	"github.com/gconnell/gopacket"
)

var (
	LayerTypeARP                  = gopacket.RegisterLayerType(10, "ARP", gopacket.DecodeFunc(decodeARP))
	LayerTypeCDP                  = gopacket.RegisterLayerType(11, "CDP", gopacket.DecodeFunc(decodeCDP))
	LayerTypeCTP                  = gopacket.RegisterLayerType(12, "CTP", gopacket.DecodeFunc(decodeCTP))
	LayerTypeCTPForwardData       = gopacket.RegisterLayerType(13, "CTPForwardData", nil)
	LayerTypeCTPReply             = gopacket.RegisterLayerType(14, "CTPReply", nil)
	LayerTypeDot1Q                = gopacket.RegisterLayerType(15, "Dot1Q", gopacket.DecodeFunc(decodeDot1Q))
	LayerTypeEtherIP              = gopacket.RegisterLayerType(16, "EtherIP", gopacket.DecodeFunc(decodeEtherIP))
	LayerTypeEthernet             = gopacket.RegisterLayerType(17, "Ethernet", gopacket.DecodeFunc(decodeEthernet))
	LayerTypeGRE                  = gopacket.RegisterLayerType(18, "GRE", gopacket.DecodeFunc(decodeGRE))
	LayerTypeICMP                 = gopacket.RegisterLayerType(19, "ICMP", gopacket.DecodeFunc(decodeICMP))
	LayerTypeIPv4                 = gopacket.RegisterLayerType(20, "IPv4", gopacket.DecodeFunc(decodeIPv4))
	LayerTypeIPv6                 = gopacket.RegisterLayerType(21, "IPv6", gopacket.DecodeFunc(decodeIPv6))
	LayerTypeLLC                  = gopacket.RegisterLayerType(22, "LLC", gopacket.DecodeFunc(decodeLLC))
	LayerTypeSNAP                 = gopacket.RegisterLayerType(23, "SNAP", gopacket.DecodeFunc(decodeSNAP))
	LayerTypeMPLS                 = gopacket.RegisterLayerType(24, "MPLS", gopacket.DecodeFunc(decodeMPLS))
	LayerTypePPP                  = gopacket.RegisterLayerType(25, "PPP", gopacket.DecodeFunc(decodePPP))
	LayerTypePPPoE                = gopacket.RegisterLayerType(26, "PPPoE", gopacket.DecodeFunc(decodePPPoE))
	LayerTypeRUDP                 = gopacket.RegisterLayerType(27, "RUDP", gopacket.DecodeFunc(decodeRUDP))
	LayerTypeSCTP                 = gopacket.RegisterLayerType(28, "SCTP", gopacket.DecodeFunc(decodeSCTP))
	LayerTypeSCTPUnknownChunkType = gopacket.RegisterLayerType(29, "SCTPUnknownChunkType", nil)
	LayerTypeSCTPData             = gopacket.RegisterLayerType(30, "SCTPData", nil)
	LayerTypeSCTPInit             = gopacket.RegisterLayerType(31, "SCTPInit", nil)
	LayerTypeSCTPSack             = gopacket.RegisterLayerType(32, "SCTPSack", nil)
	LayerTypeSCTPHeartbeat        = gopacket.RegisterLayerType(33, "SCTPHeartbeat", nil)
	LayerTypeSCTPError            = gopacket.RegisterLayerType(34, "SCTPError", nil)
	LayerTypeSCTPShutdown         = gopacket.RegisterLayerType(35, "SCTPShutdown", nil)
	LayerTypeSCTPShutdownAck      = gopacket.RegisterLayerType(36, "SCTPShutdownAck", nil)
	LayerTypeSCTPCookieEcho       = gopacket.RegisterLayerType(37, "SCTPCookieEcho", nil)
	LayerTypeSCTPEmptyLayer       = gopacket.RegisterLayerType(38, "SCTPEmptyLayer", nil)
	LayerTypeSCTPInitAck          = gopacket.RegisterLayerType(39, "LayerTypeSCTPInitAck", nil)
	LayerTypeSCTPHeartbeatAck     = gopacket.RegisterLayerType(40, "LayerTypeSCTPHeartbeatAck", nil)
	LayerTypeSCTPAbort            = gopacket.RegisterLayerType(41, "LayerTypeSCTPAbort", nil)
	LayerTypeSCTPShutdownComplete = gopacket.RegisterLayerType(42, "LayerTypeSCTPShutdownComplete", nil)
	LayerTypeSCTPCookieAck        = gopacket.RegisterLayerType(43, "LayerTypeSCTPCookieAck", nil)
	LayerTypeTCP                  = gopacket.RegisterLayerType(44, "TCP", gopacket.DecodeFunc(decodeTCP))
	LayerTypeUDP                  = gopacket.RegisterLayerType(45, "UDP", gopacket.DecodeFunc(decodeUDP))
)
